import Link from "next/link";
import { requireUser } from "../../../lib/auth/require-user";

const statuses = ["ALL", "UNPAID", "PAID", "PROCESSING", "COMPLETED", "PARTIAL", "CANCELLED", "FAILED"];
export default async function AccountOrdersPage({ searchParams }: { searchParams: Promise<{ status?: string; q?: string; page?: string }> }) {
  const { user, db } = await requireUser("/account/orders"); const params = await searchParams;
  const status = statuses.includes((params.status ?? "ALL").toUpperCase()) ? (params.status ?? "ALL").toUpperCase() : "ALL";
  const q = (params.q ?? "").trim(); const page = Math.max(1, Number.parseInt(params.page ?? "1", 10) || 1); const limit = 20;
  let query = db.from("orders").select("public_order_id,target_value,quantity,unit_price,total,currency,status,payment_status,fulfillment_status,created_at,updated_at,services(name,platforms(name))", { count: "exact" }).eq("user_id", user.id);
  if (status === "UNPAID") query = query.eq("payment_status", "UNPAID"); else if (status === "PAID") query = query.eq("payment_status", "PAID"); else if (status === "PROCESSING") query = query.eq("fulfillment_status", "PROCESSING"); else if (["COMPLETED", "PARTIAL", "CANCELLED", "FAILED"].includes(status)) query = query.eq("fulfillment_status", status);
  if (q) {
    const { data: matchingServices } = await db.from("services").select("id").ilike("name", `%${q}%`).limit(50);
    const serviceIds = (matchingServices ?? []).map((service) => service.id).join(",");
    const parts = [`public_order_id.ilike.%${q}%`, `target_value.ilike.%${q}%`];
    if (serviceIds) parts.push(`service_id.in.(${serviceIds})`);
    query = query.or(parts.join(","));
  }
  const { data: orders, count } = await query.order("created_at", { ascending: false }).range((page - 1) * limit, page * limit - 1);
  const pageCount = Math.max(1, Math.ceil((count ?? 0) / limit));
  return <><header className="dashboard-header orders-header"><p className="dashboard-kicker">ACCOUNT / ORDERS</p><h1>Your orders</h1><p>Track every order, payment, and fulfillment update in one place.</p></header><form className="orders-filters"><label className="orders-search"><span>⌕</span><input name="q" defaultValue={q} placeholder="Search by order ID or target"/></label><label><span>Status</span><select name="status" defaultValue={status}>{statuses.map((item) => <option key={item} value={item}>{item === "ALL" ? "All" : item}</option>)}</select></label><label className="orders-date"><span>Date</span><select defaultValue="30"><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="all">All time</option></select></label><button type="submit">Apply filters</button></form><section className="orders-panel"><div className="orders-panel-heading"><div><span className="catalog-eyebrow">ORDER HISTORY</span><h2>Order history</h2></div><span className="orders-total">{count ?? 0} total</span></div><div className="dashboard-table-wrap"><table className="dashboard-table orders-table"><thead><tr><th>Order ID</th><th>Service / platform</th><th>Target</th><th>Quantity</th><th>Total</th><th>Payment</th><th>Fulfillment</th><th>Created</th></tr></thead><tbody>{(orders ?? []).map((order) => <tr key={order.public_order_id}><td><Link href={`/account/orders/${order.public_order_id}`}>{order.public_order_id}</Link></td><td><strong>{(order.services as { name?: string } | null)?.name ?? "Service"}</strong><small>{(order.services as { platforms?: { name?: string } | null } | null)?.platforms?.name ?? "—"}</small></td><td>{order.target_value}</td><td>{order.quantity.toLocaleString()}</td><td>{order.total} {order.currency}</td><td><span className={`order-status ${order.payment_status.toLowerCase()}`}>{order.payment_status}</span></td><td><span className={`order-status ${order.fulfillment_status.toLowerCase()}`}>{order.fulfillment_status}</span></td><td>{new Date(order.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div>{(orders ?? []).length === 0 && <div className="orders-empty"><div className="empty-icon">V</div><h3>No orders yet</h3><p>Your order history will appear here once you place your first order.</p><Link href="/new-order">Create a new order <b>↗</b></Link></div>}<div className="orders-pagination"><span>Page {page} of {pageCount}</span><div>{page > 1 && <Link href={`/account/orders?status=${status}&q=${encodeURIComponent(q)}&page=${page - 1}`}>←</Link>}{page < pageCount && <Link href={`/account/orders?status=${status}&q=${encodeURIComponent(q)}&page=${page + 1}`}>→</Link>}</div></div></section></>;
}
