import { requireAdmin } from "../../lib/admin/auth";

export default async function AdminPage() {
  const { admin } = await requireAdmin(); if (!admin) return null;
  const db = (await import("../../lib/supabase/server")).createSupabaseAdminClient();
  const [{ count: customers }, { count: orders }, { data: wallets }, { data: recent }, { data: providerHealth }, { count: catalogCount }] = await Promise.all([
    db.from("profiles").select("id", { count: "exact", head: true }), db.from("orders").select("id", { count: "exact", head: true }), db.from("wallets").select("balance_minor").limit(1000), db.from("orders").select("public_order_id,total,currency,payment_status,fulfillment_status,created_at,profiles(email),services(name)").order("created_at", { ascending: false }).limit(10), db.from("provider_health").select("configured,balance,balance_currency,last_balance_check,balance_status").eq("provider", "reliablesmm").maybeSingle(), db.from("provider_catalog_services").select("id", { count: "exact", head: true }).eq("provider", "reliablesmm")
  ]);
  const liability = (wallets ?? []).reduce((sum, wallet) => sum + Number(wallet.balance_minor ?? 0), 0);
  return <div className="admin-overview"><header className="admin-overview-header"><div><p className="dashboard-kicker">OPERATIONS</p><h1>WELCOME BACK PLAY.ATO</h1><p>Monitor VANTA operations and manage activity in real time.</p></div><span className="admin-live-badge">● Live data</span><div className="admin-overview-mark" aria-hidden="true">V</div></header><div className="admin-summary-layout"><div className="admin-side-stats"><article className="admin-kpi-card"><span>Total orders</span><strong>{orders ?? 0}</strong><small>All time orders</small></article><article className="admin-kpi-card"><span>Customers</span><strong>{customers ?? 0}</strong><small>Registered users</small></article></div><article className="admin-wallet-focus"><span>Wallet balance</span><strong>{(liability / 100).toFixed(2)} <em>GHS</em></strong><small>Available liability across customer wallets</small><div className="admin-wallet-orbit" aria-hidden="true" /></article></div><div className="admin-overview-columns"><section className="admin-recent-panel"><div className="admin-panel-heading"><div><h2>Recent orders</h2><p>Latest customer activity across VANTA.</p></div><a href="/admin/orders">View all →</a></div>{(recent ?? []).length === 0 ? <div className="admin-empty"><div className="empty-icon">V</div><h3>No orders yet</h3><p>New customer orders will appear here.</p></div> : <div className="dashboard-table-wrap"><table className="dashboard-table"><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Status</th></tr></thead><tbody>{(recent ?? []).map((order) => <tr key={order.public_order_id}><td>{order.public_order_id}</td><td>{(order.profiles as { email?: string } | null)?.email ?? "—"}</td><td>{order.total} {order.currency}</td><td>{order.fulfillment_status}</td></tr>)}</tbody></table></div>}</section><section className="admin-provider-panel"><div className="admin-panel-heading"><div><h2>Provider health</h2><p>ReliableSMM account status.</p></div><span className={`provider-health-status ${providerHealth?.balance_status === "SUCCEEDED" ? "is-good" : ""}`}>{providerHealth?.configured ? "Configured" : "Not configured"}</span></div><div className="provider-health-grid"><div><span>Catalog</span><strong>{catalogCount ?? 0}</strong></div><div><span>Balance</span><strong>{providerHealth?.balance ?? "—"} {providerHealth?.balance_currency ?? ""}</strong></div><div><span>Status</span><strong>{providerHealth?.balance_status ?? "—"}</strong></div><div><span>Last check</span><strong>{providerHealth?.last_balance_check ? new Date(providerHealth.last_balance_check).toLocaleDateString() : "—"}</strong></div></div><small>Read-only provider monitoring. Write operations remain disabled.</small></section></div></div>;
}
