import { getInputTypeDefinition } from "./registry";
import type { ServiceInputField, ValidationConfig } from "./contracts";
import type { ProviderInputMapping } from "./contracts";
import { resolveTransform } from "./transforms";
export { normalizeComments } from "./comments";
const defaults: Record<string, ValidationConfig> = { username: { maxLength: 64 }, url: { maxLength: 2048 }, post_url: { maxLength: 2048 }, video_url: { maxLength: 2048 }, channel: { maxLength: 2048 }, page: { maxLength: 2048 }, comments: { maxLength: 10000, maxLines: 100, maxLineLength: 500 } };
const limits: Record<string, ValidationConfig> = { username: { maxLength: 64 }, url: { maxLength: 2048 }, post_url: { maxLength: 2048 }, video_url: { maxLength: 2048 }, channel: { maxLength: 2048 }, page: { maxLength: 2048 }, comments: { maxLength: 10000, maxLines: 100, maxLineLength: 500 } };
function validConfig(config: ValidationConfig | undefined, type: string) { const supplied = config ?? {}; const allowed = type === "comments" ? new Set(["maxLength", "maxLines", "maxLineLength"]) : new Set(["maxLength"]); if (Object.keys(supplied).some((key) => !allowed.has(key))) return null; const value = { ...defaults[type], ...supplied }; const maximums = limits[type]; for (const [key, n] of Object.entries(value)) if (!Number.isSafeInteger(n) || n <= 0 || n > Number(maximums[key as keyof ValidationConfig])) return null; if (type === "comments" && (!value.maxLines || !value.maxLineLength)) return null; return value; }
export function validateServiceInputField(field: ServiceInputField) { if (!field.key || !/^[a-z][a-z0-9_]{0,63}$/.test(field.key) || !field.label || field.label.length > 120 || !Number.isSafeInteger(field.displayOrder) || field.displayOrder < 0 || typeof field.required !== "boolean" || !Number.isSafeInteger(field.schemaVersion) || field.schemaVersion < 1) throw new Error("Invalid VANTA input field definition."); const definition = getInputTypeDefinition(field.inputType); if (!definition) throw new Error("Unsupported VANTA input type."); const config = validConfig(field.validation?.config, field.inputType); if (!field.validation || field.validation.rule !== definition.validationRule || !config) throw new Error("Invalid VANTA validation configuration."); return { ...field, validation: { rule: field.validation.rule, config } }; }
export function validateProviderInputMapping(mapping: ProviderInputMapping, field: ServiceInputField) { if (!mapping.serviceId || !mapping.vantaInputFieldKey || mapping.vantaInputFieldKey !== field.key || !mapping.provider || !mapping.providerServiceId || !mapping.providerParameterKey || !mapping.providerParameterKey.trim() || !Number.isSafeInteger(mapping.mappingSchemaVersion) || mapping.mappingSchemaVersion < 1 || typeof mapping.providerRequired !== "boolean" || typeof mapping.omitWhenBlank !== "boolean" || !mapping.active) throw new Error("Invalid provider input mapping."); const transform = resolveTransform(mapping.transform.id, mapping.transform.version); const type = getInputTypeDefinition(field.inputType); if (!transform || !type || transform.input !== type.valueShape) throw new Error("Provider transform is unknown or incompatible with the VANTA input type."); return mapping; }
