import { NextResponse } from "next/server";
import { requireAdmin } from "../../../../lib/admin/auth";
import { createSupabaseAdminClient } from "../../../../lib/supabase/server";
import { calculatePricing, type RateUnit } from "../../../../lib/pricing/engine";
import { enforceAdminRateLimit, limiterUnavailable } from "../../../../lib/security/rate-limit";
import { assessProviderEligibility } from "../../../../lib/targets/eligibility";
import { getTargetContract } from "../../../../lib/targets/contracts";
export async function POST(request: Request) {
 const {user,admin}=await requireAdmin(); if(!user)return NextResponse.json({error:"Authentication required."},{status:401}); if(!admin)return NextResponse.json({error:"Admin access required."},{status:403}); try{const rejected=await enforceAdminRateLimit(request,user.id,"mapping-mutation",[10,10]);if(rejected)return rejected;}catch{return limiterUnavailable()}
 const body=await request.json().catch(()=>null); const serviceId=String(body?.service_id||""); const providerServiceId=String(body?.provider_service_id||""); const sellingPrice=String(body?.selling_price||"").trim(); if(!serviceId||!/^[0-9]+$/.test(providerServiceId)||!/^[0-9]+(\.\d+)?$/.test(sellingPrice)||Number(sellingPrice)<=0)return NextResponse.json({error:"A valid provider service and positive customer price are required."},{status:400});
 const db=createSupabaseAdminClient(); const [{data:service},{data:catalog},{data:setting}]=await Promise.all([db.from("services").select("id,slug,selling_rate,currency,provider,provider_service_id,min_quantity,max_quantity").eq("id",serviceId).maybeSingle(),db.from("provider_catalog_services").select("provider,provider_service_id,name,provider_rate,provider_currency,rate_unit,provider_status,min_quantity,max_quantity,raw_metadata").eq("provider","reliablesmm").eq("provider_service_id",providerServiceId).eq("provider_status","ACTIVE").maybeSingle(),db.from("pricing_settings").select("fx_rate").eq("key","USD_GHS").maybeSingle()]);
 if(!service)return NextResponse.json({error:"VANTA service not found."},{status:404}); if(service.currency!=="GHS")return NextResponse.json({error:`VANTA service currency must be GHS; found ${service.currency||"unset"}.`},{status:409}); if(!catalog)return NextResponse.json({error:"Provider service is not active in the catalog."},{status:409}); const eligibility=assessProviderEligibility({serviceSlug:service.slug,targetContract:getTargetContract(service.slug),vantaMin:service.min_quantity,vantaMax:service.max_quantity,provider:{...catalog,provider_service_id:String(catalog.provider_service_id),name:catalog.name,provider_status:catalog.provider_status}}); if(eligibility.status!=="ELIGIBLE")return NextResponse.json({error:eligibility.status==="MANUAL_REVIEW"?"This provider service requires manual review before mapping.":"This provider service is not compatible with the VANTA service."},{status:409}); const unit=catalog.rate_unit as RateUnit; if(catalog.provider_currency!=="USD"||!["PER_UNIT","PER_1000","PER_ORDER"].includes(unit))return NextResponse.json({error:"Provider pricing unit or currency is unsupported."},{status:409});
 const economics=setting?.fx_rate ? calculatePricing({providerRate:String(catalog.provider_rate),providerRateUnit:unit,providerCurrency:"USD",fxRate:String(setting.fx_rate),sellingPricePerUnit:sellingPrice,sellingCurrency:"GHS",quantity:10000}) : null;
 const mapped=await db.rpc("apply_provider_mapping",{p_service_id:serviceId,p_provider:"reliablesmm",p_provider_service_id:providerServiceId,p_changed_by:user.id}); if(mapped.error)return NextResponse.json({error:`Provider mapping failed: ${mapped.error.message}`},{status:409}); const updated=await db.from("services").update({selling_rate:sellingPrice}).eq("id",serviceId).select("id,slug,selling_rate,currency,provider,provider_service_id").single(); if(updated.error)return NextResponse.json({error:`Provider mapping was applied, but VANTA price persistence failed: ${updated.error.message}`},{status:500}); const audit=await db.from("pricing_audit_log").insert({service_id:serviceId,field:"selling_price",old_value:service.selling_rate,new_value:sellingPrice,changed_by:user.id}); if(audit.error)return NextResponse.json({error:`VANTA price was saved, but pricing audit failed: ${audit.error.message}`},{status:500}); return NextResponse.json({saved:true,mapping:mapped.data,service:updated.data,economics,pricingPreviewUnavailable:economics===null,pricingPreviewMessage:economics===null?"USD → GHS FX is not configured.":null});
}
