import Link from "next/link";
import { requireAdmin } from "../../../lib/admin/auth";
import { SyncCatalogButton } from "./SyncCatalogButton";

export default async function ProviderCatalogPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; page?: string }> }) {
  const { admin } = await requireAdmin(); if (!admin) return null;
  const p = await searchParams; const page = Math.max(1, Number.parseInt(p.page ?? "1", 10) || 1); const limit = 50; const q = (p.q ?? "").trim();
  const db = (await import("../../../lib/supabase/server")).createSupabaseAdminClient(); let query = db.from("provider_catalog_services").select("provider,provider_service_id,name,provider_rate,provider_currency,rate_unit,min_quantity,max_quantity,refill_supported,cancel_supported,provider_status,last_synced_at", { count: "exact" }).eq("provider", "reliablesmm");
  if (p.status) query = query.eq("provider_status", p.status); if (q) query = query.or(`provider_service_id.ilike.%${q}%,name.ilike.%${q}%`);
  const { data: services, count } = await query.order("provider_service_id").range((page - 1) * limit, page * limit - 1); const pages = Math.max(1, Math.ceil((count ?? 0) / limit));
  return <><header className="dashboard-header"><p className="dashboard-kicker">PROVIDER CATALOG</p><h1>Imported services.</h1><p>Internal catalog only. Imported services are unpublished and never customer-visible by sync alone.</p></header><SyncCatalogButton /><form className="dashboard-actions"><input name="q" defaultValue={q} placeholder="Service ID or name"/><select name="status" defaultValue={p.status ?? ""}><option value="">All statuses</option><option>ACTIVE</option><option>STALE</option><option>INACTIVE</option></select><button type="submit">Filter</button></form><div className="dashboard-card"><div className="dashboard-table-wrap"><table className="dashboard-table"><thead><tr><th>ID</th><th>Name</th><th>Rate</th><th>Unit</th><th>Min / max</th><th>Refill</th><th>Cancel</th><th>Status</th><th>Synced</th></tr></thead><tbody>{(services ?? []).map((s) => <tr key={`${s.provider}-${s.provider_service_id}`}><td>{s.provider_service_id}</td><td>{s.name}</td><td>{s.provider_rate} {s.provider_currency}</td><td>{s.rate_unit}</td><td>{s.min_quantity} / {s.max_quantity}</td><td>{s.refill_supported ? "Yes" : "No"}</td><td>{s.cancel_supported ? "Yes" : "No"}</td><td>{s.provider_status}</td><td>{new Date(s.last_synced_at).toLocaleString()}</td></tr>)}</tbody></table></div><p>Page {page} of {pages} · {count ?? 0} imported records</p><div className="dashboard-actions">{page > 1 && <Link href={`/admin/provider-catalog?q=${encodeURIComponent(q)}&status=${p.status ?? ""}&page=${page - 1}`}>Previous</Link>}{page < pages && <Link href={`/admin/provider-catalog?q=${encodeURIComponent(q)}&status=${p.status ?? ""}&page=${page + 1}`}>Next</Link>}</div></div></>;
}
