import { requireAdmin } from "../../../lib/admin/auth";
import { MappingControl } from "./MappingControl";
import { PricingControl } from "./PricingControl";
const platformLogos: Record<string, string> = { Facebook: "https://cdn.simpleicons.org/facebook/1877F2", Instagram: "https://cdn.simpleicons.org/instagram/E4405F", Telegram: "https://cdn.simpleicons.org/telegram/26A5E4", TikTok: "https://cdn.simpleicons.org/tiktok/000000", YouTube: "https://cdn.simpleicons.org/youtube/FF0000", X: "https://cdn.simpleicons.org/x/FFFFFF" };
const platformLogo = (name: string) => platformLogos[name] ?? "https://cdn.simpleicons.org/sharethis/D883FF";
type Service = { id: string; slug: string; name: string; active: boolean; selling_rate: number; currency: string; provider: string | null; provider_service_id: string | null; provider_rate: number | null; provider_rate_unit: string | null; provider_currency: string | null; provider_rate_last_synced: string | null; platforms: { name?: string } | null };
export default async function AdminServicesPage() {
  const { admin } = await requireAdmin(); if (!admin) return null; const db = (await import("../../../lib/supabase/server")).createSupabaseAdminClient();
  const [{ data }, { data: setting }] = await Promise.all([db.from("services").select("id,slug,name,active,selling_rate,currency,provider,provider_service_id,provider_rate,provider_rate_unit,provider_currency,provider_rate_last_synced,platforms(name)").order("slug"), db.from("pricing_settings").select("fx_rate").eq("key", "USD_GHS").maybeSingle()]);
  const services = (data ?? []) as Service[]; const fxRate = setting?.fx_rate ? String(setting.fx_rate) : null; const categories = Array.from(services.reduce((groups, service) => { const category = service.platforms?.name ?? "Other services"; const items = groups.get(category) ?? []; items.push(service); groups.set(category, items); return groups; }, new Map<string, Service[]>()));
  return <div className="services-redesign"><header className="services-hero"><div><p className="dashboard-kicker">ADMIN / CATALOG</p><h1>Services<span>.</span></h1><p>Organize your catalog by platform and keep customer pricing, publishing, and provider mappings easy to scan.</p></div><div className="services-hero-mark" aria-hidden="true">V</div></header><section className="services-summary"><article><span>Categories</span><strong>{categories.length}</strong><small>Platforms in catalog</small></article><article><span>Total services</span><strong>{services.length}</strong><small>Available catalog records</small></article><article><span>Published</span><strong>{services.filter((service) => service.active).length}</strong><small>Customer-visible services</small></article><article><span>Unmapped</span><strong>{services.filter((service) => !service.provider).length}</strong><small>Need provider mapping</small></article></section><div className="service-category-list">{categories.map(([category, items], index) => <details className="service-category" key={category} name="service-category" open={index === 0}><summary className="service-category-heading"><span className="service-category-platform"><span className="service-category-logo"><img src={platformLogo(category)} alt="" /></span><h2>{category}</h2></span><span className="service-category-chevron" aria-hidden="true">⌄</span></summary><div className="dashboard-card service-category-card"><div className="dashboard-table-wrap"><table className="dashboard-table services-table"><thead><tr><th>Service</th><th>Customer price</th><th>Published</th><th>Provider mapping</th><th>Last sync</th><th>Action</th></tr></thead><tbody>{items.map((service) => <tr key={service.id}><td><strong>{service.name}</strong><small>{service.slug}</small></td><td>{service.selling_rate} {service.currency}</td><td><span className={`service-status ${service.active ? "is-active" : ""}`}><i />{service.active ? "Published" : "Hidden"}</span></td><td>{service.provider ? <span className="mapping-copy">{service.provider} / {service.provider_service_id}<small>{service.provider_rate} {service.provider_currency} / {service.provider_rate_unit}</small></span> : <span className="mapping-unmapped">UNMAPPED</span>}</td><td>{service.provider_rate_last_synced ? new Date(service.provider_rate_last_synced).toLocaleDateString() : "—"}</td><td><MappingControl serviceId={service.id} serviceSlug={service.slug} serviceName={service.name} current={service.provider_service_id} fxRate={fxRate}/>{service.provider && <PricingControl serviceId={service.id} sellingRate={String(service.selling_rate)} providerRate={service.provider_rate == null ? null : String(service.provider_rate)} providerRateUnit={service.provider_rate_unit} providerCurrency={service.provider_currency} fxRate={fxRate}/>}</td></tr>)}</tbody></table></div></div></details>)}</div></div>;
}
